server:
  port: 5000
security:
  user:
    password: password

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
  password: password